### PR TITLE
duplicate email bug fixed 

### LINKED ISSUE #70: Duplicate Email Bug
Fix the following
1. When a user checks for the validity of an email more than one time than duplicate emails are saving in the database.
2. Restrict the JSON content to frontend

### PR DESCRIPTION
**Pull request by nikhilbhatt**
This PR will fix #70 
1. fixed duplicate email saving to DB
2. Json content is restricted

### CODE REVIEW

**Comment by maniSHarma7575** [comment]
@ Nikhil Bhatt Please check some checks have not been passed yet.

**Review by maniSHarma7575 — APPROVED** [review]

File: app/controllers/api/v1/users_controller.rb [hunk 1]
```diff
@@ -6,12 +6,13 @@ def create
       if user.valid?
         payload = {user_id: user.id}
         token = encode_token(payload)
-        render json: { user: user, jwt: token}
+        usr= user.slice("id","name","email","username")
```
Comment (maniSHarma7575) [inline app/controllers/api/v1/users_controller.rb:9]: Please use good names for variables
```
copy_user= user.slice("id","name","email","username")
```

File: app/controllers/api/v1/users_controller.rb [hunk 2]
```diff
@@ -20,9 +21,10 @@ def login
     if user && User.authenticate(user.password,params[:password])
       payload= {user_id: user.id}
       token =encode_token(payload)
-      render json: {user: user,jwt: token, error: false, message: "Welocome back, #{user.name}"}
+      usr= user.slice("id","name","email","username")
```
Comment (maniSHarma7575) [inline app/controllers/api/v1/users_controller.rb:24]: Similiar feedback as above

**Review by maniSHarma7575 — CHANGES_REQUESTED** [review]
